### ISSUE TITLE
RFC consider pre-commit for linters

### ISSUE THREAD

**Issue by adrinjalali** [keras-team/keras#20604]
Would you consider adding `pre-commit` config to the repo? This wouldn't mean people have to enable it, but would make it possible for people who are happy to use it, to enable it and have a nicer time dealing with linting issues.

It could be a variation of this:

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.0
    hooks:
    -   id: ruff
        args: ["--fix", "--output-format=full", "--select=I"]
    -   id: ruff-format
```

To enable, the user would do:

```sh
pip install pre-commit
pre-commit install
```
